/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lsp;

/**
 *
 * @author ICT
 */

// Mengimpor semua kelas yang ada dalam paket java.sql, 
// yang menyediakan API untuk berinteraksi dengan database melalui JDBC (Java Database Connectivity).
import java.sql.*;

// Mengimpor semua kelas yang ada dalam paket javax.swing, 
// yang menyediakan berbagai komponen untuk membangun antarmuka pengguna grafis (GUI) dalam Java.
import javax.swing.*;

public class form_registrasi extends javax.swing.JFrame {
    
    // Membuka koneksi ke database melalui metode BukaKoneksi() dari kelas koneksi
    Connection conn = koneksi.BukaKoneksi();

    // Mendeklarasikan variabel 'st' sebagai objek Statement yang akan digunakan untuk mengeksekusi pernyataan SQL
    public Statement st;

    // Mendeklarasikan variabel 'rs' sebagai objek ResultSet yang akan digunakan untuk menyimpan hasil query SQL
    public ResultSet rs;

    /**
     * Creates new form form_registrasi
     */
    public form_registrasi() {
        // Memanggil method initComponents() untuk menginisialisasi komponen-komponen GUI
        initComponents();
    
        // Menentukan posisi form di tengah layar relatif terhadap form itu sendiri
        setLocationRelativeTo(this);
    }
    
    public void bersih() {
        // Mengosongkan teks di dalam JTextField 'txt_name'.
        txt_name.setText(null);
    
        // Mengosongkan teks di dalam JTextField 'txt_username'.
        txt_username.setText(null);
    
        // Mengosongkan teks di dalam JTextField 'txt_password'.
        txt_password.setText(null);
    }
    
    public void daftar() {
        try {
            // Memanggil objek 'st' dan 'conn' yang telah diinisialisasi
            st = conn.createStatement();

            // Validasi jika salah satu field kosong
            if (txt_name.getText().equals("") || 
                txt_username.getText().equals("") || 
                txt_password.getText().equals("")) {

                // Menampilkan pesan peringatan jika ada field yang kosong
                JOptionPane.showMessageDialog(null, "Data Tidak Boleh Kosong.", 
                                              "Validasi Data", JOptionPane.INFORMATION_MESSAGE);
                return;
            } else {
                // Cek apakah username sudah terdaftar di database
                String cek = "SELECT * FROM tbl_user WHERE username = '" + txt_username.getText() + "'";
                rs = st.executeQuery(cek);

                // Jika username sudah ada, tampilkan pesan peringatan
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Username sudah terdaftar.", "Validasi Data", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    // Jika username belum ada, masukkan data baru ke dalam database
                    String sql  = "INSERT INTO tbl_user (name, username, password) VALUES (?, ?, ?)";
                    PreparedStatement pstmt = conn.prepareStatement(sql);

                    // Menggunakan PreparedStatement untuk menghindari SQL Injection
                    pstmt.setString(1, txt_name.getText());
                    pstmt.setString(2, txt_username.getText());
                    pstmt.setString(3, txt_password.getText());

                    pstmt.executeUpdate();

                    // Menampilkan pesan bahwa data berhasil disimpan
                    JOptionPane.showMessageDialog(null, "Data Berhasil di Simpan.");

                    // Membersihkan field input setelah data disimpan
                    bersih();
                    
                    //membuka form login
                    new form_login().show();
                    
                    //menutup form tegister
                    this.dispose();
                }
            }
        } catch (Exception e) {
            // Tangkap exception dan tampilkan pesan error
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
        } finally {
            try {
                // Tutup ResultSet dan Statement setelah selesai digunakan
                if (rs != null) rs.close();
                if (st != null) st.close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error saat menutup resources: " + e.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        btn_close = new javax.swing.JButton();
        btn_register = new javax.swing.JButton();
        txt_password = new javax.swing.JPasswordField();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Swis721 BlkCn BT", 2, 18)); // NOI18N
        jLabel1.setText("REGISTRASI USER");

        jLabel2.setText("Password");

        jLabel3.setText("Name");

        jLabel4.setText("Username");

        txt_name.setToolTipText("");

        btn_close.setText("Close");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        btn_register.setText("Register");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        txt_password.setToolTipText("");
        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGap(4, 4, 4)
                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setSize(new java.awt.Dimension(328, 433));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        // TODO add your handling code here:
        daftar(); //memanggil variable public daftar
    }//GEN-LAST:event_btn_registerActionPerformed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        // TODO add your handling code here:
        this.dispose(); //menutup form_registrasi
    }//GEN-LAST:event_btn_closeActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
        btn_register.doClick(); //untuk menekan enter pada btn_register
    }//GEN-LAST:event_txt_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_registrasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_registrasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField txt_name;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
